# Generated by Django 6.0.3 on 2026-03-11 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
