# Generated by Django 6.0.3 on 2026-03-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_firebaseuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
