# Generated by Django 6.0.4 on 2026-04-19 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_internshipapplication_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='pg_cgpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='photo',
            field=models.FileField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='ug_cgpa',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
