# Generated by Django 6.0.7 on 2026-08-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_internshipapplication_status_jobapplication_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='firebaseuser',
            name='resume_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
