# Generated by Django 6.0.7 on 2026-09-04 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_firebaseuser_resume_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='ug_course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ug_course',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
