# Generated by Django 6.0.7 on 2026-09-09 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_internshipapplication_ug_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='pg_college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='ug_college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='pg_college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ug_college',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
