# Generated by Django 6.0.7 on 2026-09-09 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_internshipapplication_pg_college_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebaseuser',
            name='role',
        ),
    ]
