# Generated by Django 6.0.7 on 2026-09-11 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_candidatemessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemessage',
            name='calendar_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='ats_score',
            field=models.IntegerField(blank=True, default=85, null=True),
        ),
        migrations.AddField(
            model_name='internshipapplication',
            name='key_skills',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='ats_score',
            field=models.IntegerField(blank=True, default=85, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='key_skills',
            field=models.CharField(blank=True, max_length=350, null=True),
        ),
    ]
