# Generated by Django 6.0.7 on 2026-09-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_candidatemessage_calendar_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemessage',
            name='application_id',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='candidatemessage',
            name='application_type',
            field=models.CharField(db_index=True, default='job', max_length=20),
        ),
        migrations.AlterField(
            model_name='candidatemessage',
            name='candidate_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='candidatemessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='internshipapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('selected', 'Selected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected'), ('selected', 'Selected')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
