# Generated by Django 6.0.7 on 2026-09-11 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_alter_candidatemessage_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemessage',
            name='interview_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='candidatemessage',
            name='venue_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
