# Generated by Django 6.0.7 on 2026-09-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_candidatemessage_interview_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='hr_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='hr_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
