# Generated by Django 6.0.7 on 2026-09-12 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0019_internshipapplication_hr_archived_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='location',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
