# Generated by Django 6.0.7 on 2026-09-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0021_add_hr_audit_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemessage',
            name='calendar_link',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='candidatemessage',
            name='meeting_link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
