# Generated by Django 6.0.7 on 2026-09-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0024_update_15_job_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='vacancies',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
