# Generated by Django 6.0.7 on 2026-09-20 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0027_add_testing_domain_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internshipapplication',
            name='key_skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='key_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
