# Generated by Django 5.1.15 on 2026-09-22 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0029_safe_reseed_guard'),
    ]

    operations = [
        migrations.AddField(
            model_name='internshipapplication',
            name='hr_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='hr_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
