"""
management/commands/sync_knowledge_base.py
==========================================
Disadvantage #3 fix: knowledge base can now be updated via Django admin panel.

USAGE:
    .venv\\Scripts\\python.exe manage.py sync_knowledge_base
    .venv\\Scripts\\python.exe manage.py sync_knowledge_base --rebuild   # force ChromaDB rebuild

WORKFLOW:
    1. HR/admin adds/edits KnowledgeBaseItem rows in Django admin panel
    2. Run this command (or schedule it via cron / Celery beat)
    3. chat-data.txt is regenerated from the DB content
    4. ChromaDB vector index is rebuilt — chatbot immediately uses new knowledge

This replaces the old workflow of manually editing chat-data.txt + restarting the server.
"""
import logging
import os

from django.conf import settings
from django.core.management.base import BaseCommand

logger = logging.getLogger(__name__)


class Command(BaseCommand):
    help = (
        'Regenerates chat-data.txt from KnowledgeBaseItem records in the DB, '
        'then rebuilds the ChromaDB vector index so the chatbot reflects the latest knowledge.'
    )

    def add_arguments(self, parser):
        parser.add_argument(
            '--rebuild',
            action='store_true',
            default=False,
            help='Force a full ChromaDB rebuild even if chat-data.txt is unchanged.',
        )
        parser.add_argument(
            '--dry-run',
            action='store_true',
            default=False,
            help='Preview what would be written to chat-data.txt without saving.',
        )

    def handle(self, *args, **options):
        from chatbot.models import KnowledgeBaseItem

        qa_path = os.path.join(settings.BASE_DIR, 'chatbot', 'data', 'chat-data.txt')
        force_rebuild = options['rebuild']
        dry_run = options['dry_run']

        # ── Step 1: Fetch active KB items from DB ─────────────────────────────
        items = KnowledgeBaseItem.objects.filter(is_active=True).order_by('category', 'question')
        if not items.exists():
            self.stdout.write(self.style.WARNING(
                'No active KnowledgeBaseItem records found. '
                'Add items via the Django admin panel first.\n'
                'Keeping existing chat-data.txt unchanged.'
            ))
            return

        self.stdout.write(f'Found {items.count()} active KB items.')

        # ── Step 2: Build chat-data.txt content ───────────────────────────────
        lines = [
            '# ZenBot Knowledge Base',
            '# Auto-generated by: python manage.py sync_knowledge_base',
            '# DO NOT edit this file manually — edit KnowledgeBaseItem in Django admin instead.',
            '',
        ]

        current_category = None
        for item in items:
            if item.category != current_category:
                current_category = item.category
                lines.append(f'\n# ─── {current_category or "General"} ───')

            lines.append(f'\nQ: {item.question.strip()}')
            lines.append(f'A: {item.answer.strip()}')

        content = '\n'.join(lines) + '\n'

        if dry_run:
            self.stdout.write(self.style.NOTICE('DRY RUN — preview of chat-data.txt:'))
            self.stdout.write(content[:2000] + ('...(truncated)' if len(content) > 2000 else ''))
            return

        # ── Step 3: Write chat-data.txt ───────────────────────────────────────
        os.makedirs(os.path.dirname(qa_path), exist_ok=True)

        # Check if content actually changed (skip rebuild if identical)
        old_content = ''
        if os.path.exists(qa_path):
            with open(qa_path, encoding='utf-8') as f:
                old_content = f.read()

        content_changed = (content != old_content)

        if content_changed or force_rebuild:
            with open(qa_path, 'w', encoding='utf-8') as f:
                f.write(content)
            self.stdout.write(self.style.SUCCESS(
                f'chat-data.txt updated ({items.count()} Q&A pairs, {len(content)} bytes).'
            ))
        else:
            self.stdout.write('chat-data.txt is already up-to-date (no changes). Use --rebuild to force.')
            if not force_rebuild:
                return

        # ── Step 4: Rebuild ChromaDB vector index ─────────────────────────────
        self.stdout.write('Rebuilding ChromaDB vector index...')
        try:
            from chatbot.ai import ai_engine
            ai_engine._vector_db = None          # Clear in-memory cached DB
            ai_engine.get_vector_db(force_rebuild=True)
            self.stdout.write(self.style.SUCCESS(
                'ChromaDB rebuilt successfully. Chatbot is now using the updated knowledge base.'
            ))
        except RuntimeError as e:
            if 'CHROMADB_DISABLED' in str(e):
                self.stdout.write(self.style.WARNING(
                    'ChromaDB is disabled (CHROMADB_DISABLED=1). '
                    'chat-data.txt has been updated — restart your server to apply changes.'
                ))
            else:
                self.stdout.write(self.style.ERROR(f'ChromaDB rebuild failed: {e}'))
        except Exception as e:
            self.stdout.write(self.style.ERROR(
                f'ChromaDB rebuild error: {e}\n'
                'chat-data.txt was updated but vector index may be stale. Restart the server.'
            ))
